spring:
  application:
    name: productoservice

info:
  component: productoservice


server:
  port: 0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


cloud:
  services:
    registrationMethod: route

